"""empty message

Revision ID: a39627de659f
Revises: 518960442b8d
Create Date: 2020-10-03 15:12:12.759163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a39627de659f"
down_revision = "518960442b8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("complete", sa.Boolean(), nullable=True))

    op.execute(
        """
        UPDATE todos SET complete = False
        WHERE complete IS NULL;
        """
    )

    op.alter_column("todos", "complete", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "complete")
    # ### end Alembic commands ###
